import type { KnowledgeRecord } from "./Knowledge";
export type Point = { time: number; temperature: number; fan?: number };
export type Base = { id: string; createdAt: string; demo?: boolean };
export type Bean = Base & {
  name: string;
  origin: string;
  process: string;
  variety: string;
  stock: number | null;
  notes: string;
};
export type Profile = Base & { name: string; description: string };
export type Version = Base & {
  profileId: string;
  number: number;
  name: string;
  description: string;
  level: number;
  points: Point[];
  changeNote: string;
  sourceFileId?: string;
  native?: {
    kind: "profile" | "log";
    codecVersion: string;
    sourceHash: string;
    patch: Record<string, string>;
  };
};
export type Roast = Base & {
  name: string;
  beanId: string;
  profileVersionId: string;
  experimentId: string | null;
  pilotTrialId?: string | null;
  roastedAt: string;
  greenWeight: number;
  roastedWeight: number;
  duration: number;
  firstCrack: number | null;
  level: number;
  notes: string;
  points: Point[] | null;
  fileId: string | null;
  inventoryConsumed?: boolean;
  source?: { kind: string; timingNote?: string };
};
export type TastingVote = {
  taster: string;
  score: number | null;
  aroma: number | null;
  acidity: number | null;
  sweetness: number | null;
  body: number | null;
  finish: number | null;
  liking: number | null;
  targetMatch: number | null;
};
export type Cupping = Base & {
  votes?: TastingVote[];
  brewId?: string | null;
  protocolVersion?: string;
  descriptors?: string;
  blindCode?: string;
  liking?: number | null;
  targetMatch?: number | null;
  roastId: string;
  taster: string;
  tastedAt: string;
  score: number | null;
  aroma: number | null;
  acidity: number | null;
  sweetness: number | null;
  body: number | null;
  finish: number | null;
  notes: string;
};
export type Experiment = Base & {
  referenceIds?: string[];
  evidence?: KnowledgeRecord[];
  name: string;
  hypothesis: string;
  variable: string;
  status: "planned" | "active" | "complete";
  conclusion: string;
  pilot?: {
    target: string;
    method: string;
    batchSizeG: number;
    restHours: number;
    controls: string;
    lotIds: string[];
    trials: { id: string; beanId: string; condition: string }[];
  };
};
export type ArchiveFile = {
  id: string;
  name: string;
  sha256: string;
  size: number;
  createdAt: string;
};
export type DeviceRun = Base & {
  roastId?: string;
  name: string;
  roastedAt: string | null;
  duration: number | null;
  level: number | null;
  firstCrack: number | null;
  category: "recorded" | "short" | "incomplete";
  sourceFileId: string | null;
  files: { id: string; name: string; sha256: string }[];
};
export type State = {
  brews: Brew[];
  equipment: Equipment[];
  deviceRuns: DeviceRun[];
  beans: Bean[];
  profiles: Profile[];
  versions: Version[];
  roasts: Roast[];
  cuppings: Cupping[];
  experiments: Experiment[];
  files: ArchiveFile[];
};
export type Device = {
  connected: boolean;
  mode: string;
  hardwareVerified: boolean;
  profiles: { id: string; name: string; versionId: string; syncedAt: string }[];
  jobs: { id: string; name: string; status: string; completedAt: string }[];
  folder: { canImport: boolean; canStage: boolean };
};

export type Equipment = Base & {
  name: string;
  category: "brewer" | "grinder" | "roaster" | "scale" | "other";
  brand: string;
  model: string;
  configuration: string;
  calibration: string;
};
export type Brew = Base & {
  name: string;
  roastId: string;
  brewedAt: string;
  method: string;
  brewerId: string | null;
  grinderId: string | null;
  equipmentSnapshot: { brewer: Equipment | null; grinder: Equipment | null };
  grindSetting: string;
  filter: string;
  doseG: number | null;
  waterInputG: number | null;
  beverageYieldG: number | null;
  bypassWaterG: number | null;
  temperatureC: number | null;
  temperatureLocation: string;
  durationS: number | null;
  timingOrigin: string;
  pressureBar: number | null;
  waterSource: string;
  hardnessMgLCaCO3: number | null;
  alkalinityMgLCaCO3: number | null;
  tdsPercent: number | null;
  storage: string;
  protocol: string;
  notes: string;
  restHours: number | null;
};
